reporter: apiary
dry-run: null
hookfiles: null
language: nodejs
sandbox: false
server: node app.js
server-wait: 3
init: false
names: false
only: []
output: []
header: []
sorted: false
user: null
inline-errors: false
details: false
method: []
color: true
level: info
timestamp: false
silent: false
path: []
blueprint: swagger.yml
endpoint: 'http://localhost:3000'
