swagger: "2.0"
info:
  version: 1.0.0
  title: Life Saving API
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /112:
    post:
      parameters:

        - in: header
          name: content-type
          type: string
          required: true
          default: application/json; charset=utf-8

        - in: header
          name: my-freaking-request-header
          type: string
          required: true
          default: request-header-value


        - in: body
          name: body
          schema:
            type: object
            required: ['emergency']
            properties:
              emergency:
                type: boolean
                default: true

      responses:
        201:
          description: "Successful response"
          headers:
            Content-Type:   
              type: string
              default: application/json; charset=utf-8

          schema:
            type: object
            required: ['message']
            properties:
              message:
                type: string
                default: You will live!
